// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_app/test/features/marketplace/marketplace_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_app/features/marketplace/data/marketplace_repository.dart'
    as _i3;
import 'package:mobile_app/features/marketplace/models/listing.dart' as _i2;
import 'package:mobile_app/features/marketplace/models/marketplace_filters.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedListings_0 extends _i1.SmartFake
    implements _i2.PaginatedListings {
  _FakePaginatedListings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeListing_1 extends _i1.SmartFake implements _i2.Listing {
  _FakeListing_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MarketplaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarketplaceRepository extends _i1.Mock
    implements _i3.MarketplaceRepository {
  MockMarketplaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedListings> browseListings({
    _i5.MarketplaceFilters? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #browseListings,
          [],
          {
            #filters: filters,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.PaginatedListings>.value(_FakePaginatedListings_0(
          this,
          Invocation.method(
            #browseListings,
            [],
            {
              #filters: filters,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedListings>);

  @override
  _i4.Future<_i2.Listing> getListing(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getListing,
          [id],
        ),
        returnValue: _i4.Future<_i2.Listing>.value(_FakeListing_1(
          this,
          Invocation.method(
            #getListing,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Listing>);

  @override
  _i4.Future<_i2.Listing> createListing(_i2.CreateListingRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createListing,
          [request],
        ),
        returnValue: _i4.Future<_i2.Listing>.value(_FakeListing_1(
          this,
          Invocation.method(
            #createListing,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Listing>);

  @override
  _i4.Future<_i2.Listing> updateListing(
    String? id,
    _i2.UpdateListingRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateListing,
          [
            id,
            request,
          ],
        ),
        returnValue: _i4.Future<_i2.Listing>.value(_FakeListing_1(
          this,
          Invocation.method(
            #updateListing,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Listing>);

  @override
  _i4.Future<void> deleteListing(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteListing,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Listing>> getMyListings() => (super.noSuchMethod(
        Invocation.method(
          #getMyListings,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Listing>>.value(<_i2.Listing>[]),
      ) as _i4.Future<List<_i2.Listing>>);
}
