// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_app/test/features/community/community_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_app/features/community/data/community_repository.dart'
    as _i3;
import 'package:mobile_app/features/community/models/community_filter.dart'
    as _i5;
import 'package:mobile_app/features/community/models/post.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedPosts_0 extends _i1.SmartFake
    implements _i2.PaginatedPosts {
  _FakePaginatedPosts_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePost_1 extends _i1.SmartFake implements _i2.Post {
  _FakePost_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComment_2 extends _i1.SmartFake implements _i2.Comment {
  _FakeComment_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CommunityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunityRepository extends _i1.Mock
    implements _i3.CommunityRepository {
  MockCommunityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedPosts> getFeed({
    _i5.CommunityFilter? filter,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeed,
          [],
          {
            #filter: filter,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.PaginatedPosts>.value(_FakePaginatedPosts_0(
          this,
          Invocation.method(
            #getFeed,
            [],
            {
              #filter: filter,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedPosts>);

  @override
  _i4.Future<_i2.Post> getPost(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPost,
          [id],
        ),
        returnValue: _i4.Future<_i2.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #getPost,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Post>);

  @override
  _i4.Future<_i2.Post> createPost(_i2.CreatePostRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [request],
        ),
        returnValue: _i4.Future<_i2.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #createPost,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Post>);

  @override
  _i4.Future<bool> likePost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #likePost,
          [postId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.Comment> addComment(
    String? postId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            postId,
            content,
          ],
        ),
        returnValue: _i4.Future<_i2.Comment>.value(_FakeComment_2(
          this,
          Invocation.method(
            #addComment,
            [
              postId,
              content,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Comment>);

  @override
  _i4.Future<void> deletePost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [postId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportContent(_i2.CreateReportRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportContent,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
