// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_app/test/features/diy/diy_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_app/features/diy/data/diy_repository.dart' as _i2;
import 'package:mobile_app/features/diy/models/diy_filters.dart' as _i5;
import 'package:mobile_app/features/diy/models/diy_project_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedProjects_0 extends _i1.SmartFake
    implements _i2.PaginatedProjects {
  _FakePaginatedProjects_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDiyProject_1 extends _i1.SmartFake implements _i3.DiyProject {
  _FakeDiyProject_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DiyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiyRepository extends _i1.Mock implements _i2.DiyRepository {
  MockDiyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedProjects> getProjects({
    _i5.DiyFilters? filters,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
          {
            #filters: filters,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.PaginatedProjects>.value(_FakePaginatedProjects_0(
          this,
          Invocation.method(
            #getProjects,
            [],
            {
              #filters: filters,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedProjects>);

  @override
  _i4.Future<_i3.DiyProject> getProject(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProject,
          [id],
        ),
        returnValue: _i4.Future<_i3.DiyProject>.value(_FakeDiyProject_1(
          this,
          Invocation.method(
            #getProject,
            [id],
          ),
        )),
      ) as _i4.Future<_i3.DiyProject>);

  @override
  _i4.Future<void> saveProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #saveProject,
          [projectId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsaveProject(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #unsaveProject,
          [projectId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.SavedProject>> getSavedProjects() => (super.noSuchMethod(
        Invocation.method(
          #getSavedProjects,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.SavedProject>>.value(<_i2.SavedProject>[]),
      ) as _i4.Future<List<_i2.SavedProject>>);
}
