// Mocks generated by Mockito 5.4.6 from annotations
// in mobile_app/test/features/notifications/notification_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile_app/features/notifications/data/notification_repository.dart'
    as _i3;
import 'package:mobile_app/features/notifications/models/notification_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedNotifications_0 extends _i1.SmartFake
    implements _i2.PaginatedNotifications {
  _FakePaginatedNotifications_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i3.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedNotifications> getNotifications({
    bool? unreadOnly = false,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
          {
            #unreadOnly: unreadOnly,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.PaginatedNotifications>.value(
            _FakePaginatedNotifications_0(
          this,
          Invocation.method(
            #getNotifications,
            [],
            {
              #unreadOnly: unreadOnly,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedNotifications>);

  @override
  _i4.Future<int> getUnreadCount() => (super.noSuchMethod(
        Invocation.method(
          #getUnreadCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> markAsRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
