-- EcoHabit: Seed curated DIY projects
-- Reference: services/ai_service/app/services/diy_suggestions.py

INSERT INTO diy_projects (id, title, description, materials, steps, difficulty, estimated_time, estimated_price, category, video_url, source_materials, images) VALUES

('550e8400-e29b-41d4-a716-446655440001',
 'Plastic Bottle Planter',
 'Turn plastic bottles into hanging planters for your dorm room.',
 '["plastic bottle", "scissors", "rope", "paint"]',
 '["Cut the bottle in half horizontally", "Poke drainage holes in the bottom", "Paint and decorate the outside", "Thread rope through holes for hanging", "Add soil and plant"]',
 'easy',
 '30 minutes',
 150.0,
 'plastic',
 NULL,
 '["plastic"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440002',
 'Cardboard Bookshelf',
 'Create a sturdy bookshelf from layered cardboard sheets.',
 '["cardboard", "glue", "scissors", "ruler"]',
 '["Measure and cut cardboard panels", "Layer 5-6 sheets for each shelf", "Glue layers together and let dry", "Assemble shelves with vertical supports", "Reinforce joints with extra glue"]',
 'medium',
 '2 hours',
 300.0,
 'paper_cardboard',
 NULL,
 '["paper_cardboard"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440003',
 'Glass Jar Lantern',
 'Decorate glass jars into beautiful desk lanterns.',
 '["glass jar", "paint", "LED tea light", "ribbons"]',
 '["Clean the glass jar thoroughly", "Paint patterns or frost the outside", "Let paint dry completely", "Wrap ribbons around the rim", "Place LED tea light inside"]',
 'easy',
 '45 minutes',
 200.0,
 'glass',
 NULL,
 '["glass"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440004',
 'Tin Can Organizer',
 'Upcycle tin cans into desk organizers for pens and stationery.',
 '["tin can", "paint", "fabric", "glue"]',
 '["Clean and dry the tin can", "Remove any labels", "Paint the outside and let dry", "Wrap fabric around the can", "Secure fabric with glue"]',
 'easy',
 '1 hour',
 120.0,
 'metal',
 NULL,
 '["metal"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440005',
 'T-Shirt Tote Bag',
 'No-sew tote bag made from an old t-shirt.',
 '["old t-shirt", "scissors"]',
 '["Lay the t-shirt flat", "Cut off the sleeves", "Cut the neckline deeper", "Cut 2-inch strips along the bottom", "Tie strips together tightly"]',
 'easy',
 '20 minutes',
 250.0,
 'textile',
 NULL,
 '["textile"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440006',
 'Newspaper Seed Pots',
 'Biodegradable seed starter pots from newspaper.',
 '["newspaper", "water"]',
 '["Fold newspaper into strips", "Wrap strips around a small cup mold", "Tuck edges to secure", "Remove mold carefully", "Moisten slightly before planting"]',
 'easy',
 '15 minutes',
 50.0,
 'paper_cardboard',
 NULL,
 '["paper_cardboard"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440007',
 'E-Waste Sculpture',
 'Create artistic sculptures from broken electronics parts.',
 '["old circuit boards", "hot glue", "wire", "base"]',
 '["Collect and sort e-waste components", "Plan your sculpture design", "Attach pieces to base with hot glue", "Connect parts with wire for stability", "Add finishing touches and details"]',
 'hard',
 '4 hours',
 500.0,
 'ewaste',
 NULL,
 '["ewaste"]',
 '[]'),

('550e8400-e29b-41d4-a716-446655440008',
 'Cardboard Laptop Stand',
 'Ergonomic laptop stand made from reinforced cardboard.',
 '["cardboard", "tape", "scissors"]',
 '["Measure your laptop dimensions", "Cut angled support pieces", "Create triangular supports", "Cut flat shelf piece", "Tape and reinforce all joints"]',
 'medium',
 '1.5 hours',
 350.0,
 'paper_cardboard',
 NULL,
 '["paper_cardboard"]',
 '[]');
